import { randomUUID } from "node:crypto";
import { readFile } from "node:fs/promises";
import { afterAll, beforeAll, describe, expect, it, vi } from "vitest";

vi.mock("server-only", () => ({}));

import { db } from "@content-center/db";
import { MockLLMProvider } from "@content-center/providers";
import { AIControlService } from "../server/ai/control/ai-control-service";
import { ModelRouter } from "../server/ai/control/model-router";
import { ProjectContextBuilder } from "../server/ai/project-context";
import { decideCreatorProfileSuggestion, decideMethodSuggestion, generateCreatorProfileSuggestions, generateMethodSuggestions, listCreatorProfileSuggestions } from "../server/learning-suggestions/service";

describe("Phase 10D-2 learning suggestions", () => {
  const suffix = randomUUID(); const ownerId = `learning-owner-${suffix}`; const viewerId = `learning-viewer-${suffix}`; let workspaceId = ""; let accountId = ""; let studyId = ""; const sampleIds: string[] = []; const revisionIds: string[] = []; let providerOutput: unknown = {};
  const provider = new MockLLMProvider(() => providerOutput); const runtime = { provider, providerName: "KIMI", model: "kimi-k2.6", requestedModel: "kimi-k2.6", mode: "REAL" as const }; const controlService = new AIControlService({ modelRouter: new ModelRouter(async () => runtime) });

  beforeAll(async () => {
    await db.user.createMany({ data: [{ id: ownerId, name: "Learning Owner", email: `${ownerId}@example.test` }, { id: viewerId, name: "Learning Viewer", email: `${viewerId}@example.test` }] });
    const workspace = await db.workspace.create({ data: { name: "Learning", slug: `learning-${suffix}`, members: { create: [{ userId: ownerId, role: "OWNER" }, { userId: viewerId, role: "VIEWER" }] } } }); workspaceId = workspace.id;
    accountId = (await db.benchmarkAccount.create({ data: { workspaceId, platform: "DOUYIN", externalAccountId: `account-${suffix}`, name: "真实研究账号", createdById: ownerId } })).id;
    const study = await db.benchmarkStudy.create({ data: { workspaceId, benchmarkAccountId: accountId, createdById: ownerId, version: 1, status: "COMPLETED", sampleCount: 3, insufficientSamples: false } }); studyId = study.id;
    for (let index = 0; index < 3; index += 1) {
      const quote = `样本${index + 1}先给判断再解释原因。`; const source = await db.sourceItem.create({ data: { workspaceId, createdById: ownerId, sourceType: "VIDEO", sourcePlatform: "DOUYIN", sourceProvider: "REDFOX", title: `外部样本 ${index + 1}`, status: "READY", transcript: { create: { workspaceId, provider: "FIXTURE", providerMode: "REAL", fullText: quote, segments: [{ startMs: index * 1000, endMs: index * 1000 + 900, text: quote }] } } } }); const transcript = await db.transcript.findUniqueOrThrow({ where: { sourceItemId: source.id } }); const analysis = await db.materialAnalysis.create({ data: { workspaceId, sourceItemId: source.id, createdById: ownerId, version: 1, status: "COMPLETED", tags: [], keywords: [], keyPoints: [], transcriptUpdatedAtAtAnalysis: transcript.updatedAt, understanding: { section: { evidence: [{ quote }] } } } }); const sample = await db.benchmarkStudySample.create({ data: { studyId, sourceItemId: source.id, materialAnalysisId: analysis.id } }); sampleIds.push(sample.id);
    }
    await db.benchmarkStudy.update({ where: { id: studyId }, data: { output: { topicDirections: [], openingPatterns: [], structures: [], persuasionMethods: [], expressionHabits: [], endings: [], commonMethods: [{ title: "先给判断再解释", howTo: ["开头先说清核心判断", "随后解释依据"], applicable: ["观点型内容"], boundaries: ["没有依据时不要下绝对结论"], occurrenceSampleIds: sampleIds, exceptionSampleIds: [], evidence: sampleIds.map((sampleId, index) => ({ sampleId, quote: `样本${index + 1}先给判断再解释原因。` })) }], exceptions: [], repeatedCaseNotes: [], stableMethodsFound: true, message: "三个样本反复出现。" } } });
    await db.creatorProfile.create({ data: { workspaceId, userId: ownerId, displayName: "Learning Owner", coreTopics: [], personalViews: [], brandTerms: [], forbiddenTerms: [], hookPreferences: [], structurePreferences: [], ctaPreferences: [], examplePhrases: [] } });
    for (let index = 0; index < 5; index += 1) { const project = await db.contentProject.create({ data: { workspaceId, createdById: ownerId, title: `确认稿项目 ${index + 1}` } }); const branch = await db.draftBranch.create({ data: { workspaceId, projectId: project.id, title: "主稿", workingTitle: `确认稿 ${index + 1}`, workingBody: `我先说结论，第 ${index + 1} 篇确认稿直接进入判断。`, workingOutline: [], createdById: ownerId, updatedById: ownerId } }); const revision = await db.draftRevision.create({ data: { workspaceId, projectId: project.id, draftBranchId: branch.id, revision: 1, title: branch.workingTitle, body: branch.workingBody, outline: [], origin: "HUMAN", createdById: ownerId } }); await db.draftBranch.update({ where: { id: branch.id }, data: { currentRevisionId: revision.id, confirmedRevisionId: revision.id } }); revisionIds.push(revision.id); }
  });

  afterAll(async () => { await db.methodAsset.deleteMany({ where: { workspaceId } }); await db.benchmarkStudy.deleteMany({ where: { workspaceId } }); await db.workspace.delete({ where: { id: workspaceId } }); await db.user.deleteMany({ where: { id: { in: [ownerId, viewerId] } } }); await db.$disconnect(); });

  it("creates grounded multi-sample method suggestions, dedupes, and saves through MethodAsset", async () => {
    providerOutput = { suggestions: [{ sourceMethodIndex: 0, type: "OPENING", rationale: "三条内容都采用这一顺序。" }] };
    const first = await generateMethodSuggestions({ workspaceId, userId: ownerId, benchmarkAccountId: accountId, benchmarkStudyId: studyId }, { controlService }); const second = await generateMethodSuggestions({ workspaceId, userId: ownerId, benchmarkAccountId: accountId, benchmarkStudyId: studyId }, { controlService }); expect(first.created).toBe(1); expect(second.created).toBe(0); expect(first.items[0]).toMatchObject({ stability: "STABLE", sampleCount: 3, status: "PENDING" });
    const suggestion = first.items[0]!; await expect(decideMethodSuggestion({ workspaceId, userId: viewerId, suggestionId: suggestion.id, decision: "SAVE" })).rejects.toMatchObject({ code: "FORBIDDEN" }); const saved = await decideMethodSuggestion({ workspaceId, userId: ownerId, suggestionId: suggestion.id, decision: "SAVE", title: "先给判断再解释", steps: ["先说判断", "再讲依据"], applicableScenarios: ["观点型内容"], boundaries: ["不能虚构依据"] }); if (saved.status !== "ACCEPTED" || !saved.method) throw new Error("method suggestion was not saved"); expect(saved.method).toMatchObject({ status: "SAVED", current: { source: { benchmarkStudyId: studyId } } }); expect(saved.method.current.source.title).toContain("3 条代表内容研究"); expect(await db.methodVersion.findFirst({ where: { assetId: saved.method.id, workspaceDefaultKey: { not: null } } })).toBeNull();
  });

  it("labels a low-support research suggestion as limited and rejection never creates a method", async () => {
    const lowStudy = await db.benchmarkStudy.create({ data: { workspaceId, benchmarkAccountId: accountId, createdById: ownerId, version: 2, status: "COMPLETED", sampleCount: 1, insufficientSamples: true, samples: { create: { sourceItemId: (await db.benchmarkStudySample.findFirstOrThrow({ where: { studyId } })).sourceItemId } }, output: { topicDirections: [], openingPatterns: [], structures: [], persuasionMethods: [], expressionHabits: [], endings: [], commonMethods: [{ title: "单样本写法", howTo: ["只作为尝试"], applicable: ["探索"], boundaries: ["不能当作稳定规律"], occurrenceSampleIds: [], exceptionSampleIds: [], evidence: [] }], exceptions: [], repeatedCaseNotes: [], stableMethodsFound: true, message: "来源较少。" } } }); const sample = await db.benchmarkStudySample.findFirstOrThrow({ where: { studyId: lowStudy.id } }); await db.benchmarkStudy.update({ where: { id: lowStudy.id }, data: { output: { topicDirections: [], openingPatterns: [], structures: [], persuasionMethods: [], expressionHabits: [], endings: [], commonMethods: [{ title: "单样本写法", howTo: ["只作为尝试"], applicable: ["探索"], boundaries: ["不能当作稳定规律"], occurrenceSampleIds: [sample.id], exceptionSampleIds: [], evidence: [{ sampleId: sample.id, quote: "样本1先给判断再解释原因。" }] }], exceptions: [], repeatedCaseNotes: [], stableMethodsFound: true, message: "来源较少。" } } }); providerOutput = { suggestions: [{ sourceMethodIndex: 0, type: "OPENING", rationale: "目前只有一个样本。" }] }; const result = await generateMethodSuggestions({ workspaceId, userId: ownerId, benchmarkAccountId: accountId, benchmarkStudyId: lowStudy.id }, { controlService }); expect(result.items.find(({ studyId: id }) => id === lowStudy.id)).toMatchObject({ stability: "LIMITED", stabilityLabel: "目前只在少量样本中看到" }); const candidate = result.items.find(({ studyId: id }) => id === lowStudy.id)!; const methodsBefore = await db.methodAsset.count({ where: { workspaceId } }); await decideMethodSuggestion({ workspaceId, userId: ownerId, suggestionId: candidate.id, decision: "REJECT" }); expect(await db.methodAsset.count({ where: { workspaceId } })).toBe(methodsBefore);
  });

  it("uses only five confirmed drafts, keeps suggestions pending, and applies only after acceptance", async () => {
    let captured = ""; providerOutput = { suggestions: [{ type: "HOOK_PREFERENCE", proposedValue: "更偏好直接判断式开头", rationale: "五篇确认稿都直接进入判断。", evidenceRevisionIds: revisionIds.slice(0, 5) }, { type: "FORBIDDEN_STYLE", proposedValue: "避免宏大背景铺垫", rationale: "确认稿没有使用背景铺垫。", evidenceRevisionIds: revisionIds.slice(0, 3) }] }; const capturing = new MockLLMProvider((input) => { captured = input.prompt; return providerOutput; }); const service = new AIControlService({ modelRouter: new ModelRouter(async () => ({ ...runtime, provider: capturing })) }); const before = await db.creatorProfile.findUniqueOrThrow({ where: { workspaceId_userId: { workspaceId, userId: ownerId } } }); const generated = await generateCreatorProfileSuggestions({ workspaceId, userId: ownerId }, { controlService: service }); expect(generated.created).toBe(2); expect(captured).toContain(revisionIds[0]!); expect(captured).not.toContain("REDFOX"); expect((await db.creatorProfile.findUniqueOrThrow({ where: { id: before.id } })).hookPreferences).toEqual([]); const pending = (await listCreatorProfileSuggestions({ workspaceId, userId: ownerId })).find(({ type }) => type === "HOOK_PREFERENCE")!; await expect(decideCreatorProfileSuggestion({ workspaceId, userId: viewerId, suggestionId: pending.id, decision: "ACCEPT" })).rejects.toMatchObject({ code: "FORBIDDEN" }); await decideCreatorProfileSuggestion({ workspaceId, userId: ownerId, suggestionId: pending.id, decision: "ACCEPT" }); expect((await db.creatorProfile.findUniqueOrThrow({ where: { id: before.id } })).hookPreferences).toContain("更偏好直接判断式开头"); const rejected = (await listCreatorProfileSuggestions({ workspaceId, userId: ownerId })).find(({ type }) => type === "FORBIDDEN_STYLE")!; await decideCreatorProfileSuggestion({ workspaceId, userId: ownerId, suggestionId: rejected.id, decision: "REJECT" }); expect((await db.creatorProfile.findUniqueOrThrow({ where: { id: before.id } })).forbiddenStyle).toBe(""); const audit = await db.auditLog.findFirstOrThrow({ where: { action: "creator_profile_suggestion.accepted", resourceId: pending.id } }); expect(audit.metadata).toMatchObject({ before: [], after: ["更偏好直接判断式开头"], evidenceRefs: revisionIds.slice(0, 5) });
  });

  it("requires the stability threshold and keeps the migration additive", async () => {
    const sparseUser = await db.user.create({ data: { id: `sparse-${suffix}`, name: "Sparse", email: `sparse-${suffix}@example.test`, workspaceMemberships: { create: { workspaceId, role: "EDITOR" } } } }); const result = await generateCreatorProfileSuggestions({ workspaceId, userId: sparseUser.id }, { controlService }); expect(result).toMatchObject({ created: 0, reason: expect.stringContaining("更多已确认稿件") }); const migration = await readFile(new URL("../../../packages/db/prisma/migrations/20260913213000_method_profile_suggestions/migration.sql", import.meta.url), "utf8"); expect(migration).toContain('CREATE TABLE "MethodSuggestion"'); expect(migration).toContain('CREATE TABLE "CreatorProfileSuggestion"'); expect(migration).not.toMatch(/DROP TABLE|DROP COLUMN/u); await db.user.delete({ where: { id: sparseUser.id } });
  });

  it("does not let a pending profile suggestion influence creation context", async () => {
    const profile = await db.creatorProfile.findUniqueOrThrow({ where: { workspaceId_userId: { workspaceId, userId: ownerId } } }); const project = await db.contentProject.findFirstOrThrow({ where: { workspaceId, createdById: ownerId } }); const proposedValue = "仅存在于待处理建议中的独特表达"; await db.creatorProfileSuggestion.create({ data: { workspaceId, creatorProfileId: profile.id, targetUserId: ownerId, type: "PREFERRED_STYLE", currentValue: "", proposedValue, rationale: "测试待处理隔离", evidenceRefs: revisionIds.slice(0, 3), sampleCount: 3, dedupeKey: `pending-context-${suffix}`, generatedById: ownerId } }); const context = await new ProjectContextBuilder().build({ workspaceId, userId: ownerId, projectId: project.id, action: "PROJECT_ASSISTANT" }); expect(JSON.stringify(context.context)).not.toContain(proposedValue);
  });
});
