import { randomUUID } from "node:crypto";
import { mkdir, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { chromium, type Browser, type BrowserContext } from "@playwright/test";
import { afterAll, beforeAll, expect, it, onTestFailed, vi } from "vitest";
vi.mock("server-only", () => ({}));
import { db } from "@content-center/db";
import { auth } from "../lib/auth";
import { createTextArtifact, getArtifactForUser } from "../server/artifacts/service";
const origin = "http://127.0.0.1:3020";
let browser: Browser, context: BrowserContext, workspaceId = "", userId = "", projectId = "", sourceId = "", emptySourceId = "", sessionId = "", runId = "", artifactId = "", output = "";
const completed: string[] = []; let assistantPosts = 0;
beforeAll(async () => {
  const target = process.env.FINAL_ACCEPTANCE_OUTPUT || "", url = new URL(process.env.DATABASE_URL!);
  if (process.env.ENVIRONMENT_ID !== "LOCAL_REVIEW" || url.port !== "55436" || url.pathname !== "/content_center_upgrade_review" || !target.startsWith("output/research-core-20261006/iteration-")) throw Error("ISOLATED_RESEARCH_CORE_ONLY");
  output = resolve(target, "browser-" + Date.now()); await mkdir(output, { recursive: true });
  const email = "core-browser-" + randomUUID() + "@example.test", password = "fixture-" + randomUUID();
  userId = (await auth.api.signUpEmail({ body: { name: "隔离来源测试", email, password } })).user.id;
  workspaceId = (await db.workspace.create({ data: { name: "研究来源隔离验收", slug: randomUUID(), members: { create: { userId, role: "OWNER" } } } })).id;
  projectId = (await db.contentProject.create({ data: { workspaceId, createdById: userId, title: "隔离项目：保留原输入" } })).id;
  const thread = await db.assistantThread.create({ data: { workspaceId, projectId, createdById: userId } });
  await db.assistantMessage.create({ data: { threadId: thread.id, role: "USER", content: "正常创作对话不要删除", status: "COMPLETED" } });
  const assistant = await db.assistantMessage.create({ data: { threadId: thread.id, role: "ASSISTANT", content: "已经写好的真实测试成果正文。", status: "COMPLETED", metadata: { resultType: "DRAFT" } } });
  artifactId = (await createTextArtifact({ workspaceId, userId, projectId, title: "必须保留的成果", sourceMessageId: assistant.id })).artifactId;
  sourceId = (await db.sourceItem.create({ data: { workspaceId, createdById: userId, sourceType: "TEXT", sourcePlatform: "GENERIC", title: "ab123456789012345678901234_raw", rawText: "这是原内容，可核查摘录和证据。研究不应该自动刷进创作聊天。", status: "READY", createdAt: new Date("2026-01-01"), updatedAt: new Date("2026-01-01") } })).id;
  emptySourceId = (await db.sourceItem.create({ data: { workspaceId, createdById: userId, sourceType: "TEXT", sourcePlatform: "GENERIC", title: null, status: "READY", createdAt: new Date("2026-01-02"), updatedAt: new Date("2026-01-02") } })).id;
  sessionId = (await db.researchSession.create({ data: { workspaceId, createdById: userId, title: "隔离私人研究", entryTemplate: "DIRECT", requestKey: randomUUID() } })).id;
  runId = (await db.researchRun.create({ data: { workspaceId, sessionId, requestedById: userId, question: "只选择本次发现", requestKey: randomUUID(), requestHash: "fixture", version: 1, status: "COMPLETED", stage: "COMPLETED", inputScope: { materialIds: [sourceId], benchmarkAccountIds: [], trendKeys: [], notes: "", useCreatorProfile: false, useOwnArtifacts: false }, blocks: [
    { id: "finding", type: "text", title: "有用发现", text: "明确选中的方法，而不是整份报告。", provenance: "AI_INTERPRETATION", sourceRefs: [], limitation: "隔离示例" },
    { id: "not-chosen", type: "text", title: "其他私人发现", text: "本次不选择的私人观点", provenance: "AI_INTERPRETATION", sourceRefs: [], limitation: "不要自动携带" },
  ], sourceRefs: [] } })).id;
  await writeFile(resolve(output, "fixture-ids.json"), JSON.stringify({ workspaceId, userId, projectId, sourceId, emptySourceId, sessionId, runId, artifactId }, null, 2));
  const signin = await auth.api.signInEmail({ body: { email, password }, asResponse: true }); expect(signin.ok).toBe(true);
  browser = await chromium.launch({ channel: "msedge", headless: true }); context = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
  await context.addCookies(signin.headers.getSetCookie().map(value => { const pair = value.split(";")[0]!, at = pair.indexOf("="); return { name: pair.slice(0, at), value: pair.slice(at + 1), url: origin }; }));
  context.on("request", request => { if (request.method() === "POST" && /\/api\/projects\/[^/]+\/(?:assistant|artifacts)(?:\/|$)/.test(new URL(request.url()).pathname)) assistantPosts++; });
}, 90000);
afterAll(async () => {
  await Promise.allSettled([context?.close(), browser?.close()]);
  if (workspaceId) await db.workspace.deleteMany({ where: { id: workspaceId } });
  if (userId) await db.user.deleteMany({ where: { id: userId } });
  const clean = !workspaceId || await db.workspace.count({ where: { id: workspaceId } }) === 0;
  if (output) await writeFile(resolve(output, "evidence.json"), JSON.stringify({ completed, assistantPosts, fixtureCleanupVerified: clean, formalBusinessWrites: 0, externalCalls: 0, originalUserPasswordUsed: false }, null, 2));
  expect(clean).toBe(true); await db.$disconnect();
}, 60000);
async function pageFor(path: string) {
  const page = await context.newPage(); page.setDefaultTimeout(25000);
  onTestFailed(async () => { await page.screenshot({ path: resolve(output, "failure-" + randomUUID() + ".png"), fullPage: true, timeout: 3000 }).catch(() => undefined); await page.close(); });
  expect((await page.goto(origin + path, { waitUntil: "domcontentloaded" }))?.status()).toBe(200); return page;
}
async function creativeSnapshot() { return JSON.stringify({ messages: await db.assistantMessage.findMany({ where: { thread: { projectId } }, orderBy: { id: "asc" } }), artifact: await getArtifactForUser({ workspaceId, userId, projectId, artifactId }) }); }
it("daily shows actual excerpts/old dates and sensible unnamed labels on desktop and narrow screens", async () => {
  const before = await creativeSnapshot(), page = await pageFor("/research");
  await page.getByRole("heading", { name: "今天，从已有内容开始" }).waitFor();
  expect(await page.locator(".research-source-card").count()).toBe(2);
  expect(await page.locator(".research-source-list").innerText()).toContain("2026/1/1");
  expect(await page.locator(".research-source-list").innerText()).not.toContain("_raw");
  expect(await page.getByText("暂无可读正文", { exact: true }).count()).toBe(1);
  await page.screenshot({ path: resolve(output, "daily-desktop.png"), fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 2)).toBe(true);
  await page.screenshot({ path: resolve(output, "daily-mobile.png"), fullPage: true });
  expect(await creativeSnapshot()).toBe(before); completed.push("daily-real-sources-desktop-mobile"); await page.close();
}, 120000);
it("explicit bookmark and unread actions persist without assistant writes or automatic read on open", async () => {
  const before = await creativeSnapshot(), page = await pageFor("/research/sources/" + sourceId);
  expect(await page.locator(".research-source-original").innerText()).toContain("可核查摘录");
  expect(await db.researchObjectPreference.count({ where: { workspaceId, userId, kind: "MATERIAL" } })).toBe(0);
  await page.getByRole("button", { name: "收藏来源", exact: true }).click();
  await page.getByRole("button", { name: "已收藏 · 取消", exact: true }).waitFor();
  await page.getByRole("button", { name: "标记已读", exact: true }).click();
  await page.getByRole("button", { name: "标为未读", exact: true }).waitFor();
  await page.reload(); await page.getByRole("button", { name: "标为未读", exact: true }).waitFor();
  await page.getByRole("button", { name: "标为未读", exact: true }).click();
  await page.getByRole("button", { name: "标记已读", exact: true }).waitFor();
  await page.screenshot({ path: resolve(output, "source-original.png"), fullPage: true });
  expect(await creativeSnapshot()).toBe(before); expect(assistantPosts).toBe(0); completed.push("read-bookmark-refresh-no-creative-writes"); await page.close();
}, 120000);
it("explicit new research supports original selection and failed submit/retry stays out of creative history", async () => {
  const before = await creativeSnapshot(), page = await pageFor("/research?entry=BREAKDOWN&material=" + sourceId);
  await page.waitForURL(url => url.pathname === "/research/new");
  await page.waitForFunction(() => document.querySelector(".research-composer")?.getAttribute("data-ready") === "true");
  await page.getByLabel("你想研究什么？", { exact: true }).fill("请只在研究里分析原内容");
  let attempts = 0;
  await page.route(/\/api\/research\/sessions\/[^/]+\/runs$/, async route => { attempts++; await route.fulfill({ status: 503, contentType: "application/json", body: JSON.stringify({ message: "隔离故障：外调暂停，未执行研究" }) }); });
  await page.getByRole("button", { name: "开始研究", exact: true }).click();
  await page.getByRole("alert").filter({ hasText: "隔离故障" }).waitFor();
  expect(await page.getByLabel("你想研究什么？", { exact: true }).inputValue()).toContain("只在研究里");
  await page.getByRole("button", { name: "开始研究", exact: true }).click();
  await expect.poll(() => attempts).toBe(2);
  expect(await creativeSnapshot()).toBe(before); expect(assistantPosts).toBe(0); completed.push("research-submit-failure-retry-isolated"); await page.close();
}, 120000);
it("findings start unselected; open/close/cancel and refresh create no project content", async () => {
  const before = await creativeSnapshot(), page = await pageFor("/research/results/run/" + runId);
  expect(await page.locator(".research-legacy-creation").count()).toBe(0);
  await page.waitForFunction(() => document.querySelector(".research-use-findings")?.getAttribute("data-ready") === "true");
  await page.getByRole("button", { name: "用这些发现创作", exact: true }).click();
  const panel = page.locator(".research-findings-panel");
  await panel.getByRole("button", { name: "带入项目，先审阅", exact: true }).waitFor();
  expect(await panel.locator('fieldset input[type="checkbox"]:checked').count()).toBe(0);
  expect(await panel.getByRole("button", { name: "带入项目，先审阅", exact: true }).isDisabled()).toBe(true);
  await page.getByRole("button", { name: "取消本次准备", exact: true }).click(); await page.reload();
  expect(await creativeSnapshot()).toBe(before); expect(assistantPosts).toBe(0); completed.push("prepare-cancel-does-not-create-or-share"); await page.close();
}, 120000);
it("confirmed selected handoff preserves old input; cancellation in project never sends or edits the Artifact", async () => {
  const before = await creativeSnapshot(), page = await pageFor("/research/results/run/" + runId);
  await page.evaluate(({ workspaceId, userId, projectId }) => sessionStorage.setItem("research-creation:" + workspaceId + ":" + userId + ":" + projectId + ":composer", JSON.stringify({ actor: { workspaceId, userId }, projectId, expiresAt: Date.now() + 1800000, draft: { input: "已有未发送输入，不能覆盖", references: [], materialIds: [], skillId: "", modelId: "" } })), { workspaceId, userId, projectId });
  await page.waitForFunction(() => document.querySelector(".research-use-findings")?.getAttribute("data-ready") === "true");
  await page.getByRole("button", { name: "用这些发现创作", exact: true }).click();
  const panel = page.locator(".research-findings-panel"); await panel.getByLabel("有用发现", { exact: true }).check();
  await panel.getByLabel("研究使用项目", { exact: true }).selectOption(projectId);
  await panel.getByRole("button", { name: "带入项目，先审阅", exact: true }).click();
  await page.waitForURL(url => url.pathname === "/dashboard");
  const handoff = page.getByRole("region", { name: "审阅研究带入内容" });
  await page.locator(".agent-research-handoff").waitFor();
  expect(await page.getByRole("textbox", { name: "和鑫小助说", exact: true }).inputValue()).toBe("已有未发送输入，不能覆盖");
  expect(await page.locator(".agent-research-handoff").innerText()).not.toContain("本次不选择的私人观点");
  await page.locator(".agent-research-handoff").getByRole("button", { name: /取消/ }).click();
  expect(await page.getByRole("textbox", { name: "和鑫小助说", exact: true }).inputValue()).toBe("已有未发送输入，不能覆盖");
  expect(await creativeSnapshot()).toBe(before); expect(assistantPosts).toBe(0); completed.push("confirmed-reference-handoff-cancel-preserves-input-artifact"); await page.close(); void handoff;
}, 120000);
it("manual account purpose saves locally while external query and collection remain visibly paused", async () => {
  const before = await creativeSnapshot(), page = await pageFor("/research/benchmarks");
  await page.waitForFunction(() => document.querySelector(".research-benchmark-add")?.getAttribute("data-ready") === "true");
  await page.getByText("添加老师 / 对标账号", { exact: true }).click();
  const form = page.getByRole("form", { name: "手工跟踪账号" });
  await form.getByLabel("账号名称", { exact: true }).fill("隔离示例：手工老师");
  await form.getByLabel("真实平台账号 ID", { exact: true }).fill("fixture-" + randomUUID());
  await form.getByLabel("跟踪目的（工作空间成员可见）", { exact: true }).fill("只学习解释顺序，不虚构同步作品");
  await form.getByRole("button", { name: "保存跟踪账号", exact: true }).click();
  await page.waitForURL(url => /^\/research\/benchmarks\/[^/]+$/.test(url.pathname));
  expect(await page.getByText("只学习解释顺序，不虚构同步作品", { exact: true }).count()).toBe(1);
  await page.locator(".dossier-update summary").click();
  expect(await page.getByRole("button", { name: "采集已暂停", exact: true }).isDisabled()).toBe(true);
  await page.screenshot({ path: resolve(output, "manual-account-paused.png"), fullPage: true });
  expect(await creativeSnapshot()).toBe(before); expect(assistantPosts).toBe(0); completed.push("manual-account-no-collection"); await page.close();
}, 120000);

it("private clipping cancel, save and explicit topic adoption never leak private notes or create creative messages", async () => {
  const before = await creativeSnapshot(), page = await pageFor("/research/sources/" + sourceId);
  await page.waitForFunction(() => document.querySelector('[aria-label="摘录与选题"]')?.getAttribute("data-ready") === "true");
  await page.getByRole("button", { name: "保存原文摘录 / 写备注", exact: true }).click();
  await page.getByLabel("原文摘录", { exact: true }).fill("这是原内容，可核查摘录和证据。");
  await page.getByLabel("我的备注", { exact: true }).fill("仅本人可见的特殊备注");
  await page.getByRole("button", { name: "取消本次保存", exact: true }).click();
  expect(await db.researchRun.count({ where: { workspaceId, coverage: { path: ["manualClipping"], equals: true } } })).toBe(0);
  await page.getByRole("button", { name: "保存原文摘录 / 写备注", exact: true }).click();
  await page.getByRole("button", { name: "确认保存私人摘录", exact: true }).click();
  await page.getByRole("status").filter({ hasText: "私人研究" }).waitFor();
  expect(await db.researchRun.count({ where: { workspaceId, coverage: { path: ["manualClipping"], equals: true } } })).toBe(1);
  await page.getByRole("button", { name: "作为候选选题", exact: true }).click();
  expect(await page.getByLabel("入选题理由", { exact: true }).inputValue()).toBe("");
  await page.getByLabel("候选选题", { exact: true }).fill("明确采用的隔离候选");
  expect(await page.getByRole("button", { name: "确认入选题", exact: true }).isDisabled()).toBe(true);
  await page.getByLabel("入选题理由", { exact: true }).fill("只分享我明确填写的这段");
  await page.getByRole("checkbox", { name: /我确认选题标题/ }).check();
  await page.getByRole("button", { name: "确认入选题", exact: true }).click();
  await page.getByRole("status").filter({ hasText: "选题已保存" }).waitFor();
  await page.reload(); await page.getByText(/已有候选选题 · 1 项/).waitFor();
  await page.getByRole("button", { name: "作为候选选题", exact: true }).click();
  await page.getByLabel("候选选题", { exact: true }).fill("明确采用的隔离候选");
  await page.getByRole("checkbox", { name: /我确认选题标题/ }).check();
  await page.getByRole("button", { name: "确认入选题", exact: true }).click();
  await page.getByRole("status").filter({ hasText: "选题已保存" }).waitFor();
  const ideas = await db.contentIdea.findMany({ where: { workspaceId } });
  expect(ideas).toHaveLength(1); expect(ideas[0]!.description).toBe("只分享我明确填写的这段");
  expect(JSON.stringify(ideas)).not.toContain("仅本人可见的特殊备注");
  await page.screenshot({ path: resolve(output, "clippings-adopted-private.png"), fullPage: true });
  expect(await creativeSnapshot()).toBe(before); expect(assistantPosts).toBe(0);
  completed.push("clipping-private-cancel-save-explicit-adoption-deduplication"); await page.close();
}, 120000);
it("works queue renders saved ordinary works, missing dates, own unread state and existing adopted topic", async () => {
  const before = await creativeSnapshot();
  const account = await db.benchmarkAccount.create({ data: { workspaceId, createdById: userId, platform: "DOUYIN", externalAccountId: randomUUID(), name: "普通作品老师", researchNotes: "研究如何讲清楚", lastSyncedAt: new Date("2026-01-03") } });
  const work = await db.benchmarkContentSnapshot.create({ data: { workspaceId, benchmarkAccountId: account.id, platform: "DOUYIN", externalId: randomUUID(), title: "普通作品也能研究", url: "https://example.test/ordinary-work", metadata: {}, publishedAt: new Date() } });
  await db.benchmarkContentSnapshot.create({ data: { workspaceId, benchmarkAccountId: account.id, platform: "DOUYIN", externalId: randomUUID(), title: "没有发布时间的作品", url: "https://example.test/unknown-date", metadata: {} } });
  await db.sourceItem.update({ where: { id: sourceId }, data: { sourcePlatform: "DOUYIN", externalId: work.externalId } });
  const page = await pageFor("/research/works");
  await page.getByRole("heading", { name: "新作品，逐条读懂", exact: true }).waitFor();
  const card = page.locator(".research-source-card").filter({ has: page.getByRole("heading", { name: "普通作品也能研究", exact: true }) });
  await card.waitFor();
  await card.locator(".research-source-actions[data-ready=\"true\"]").waitFor();
  expect(await card.innerText()).toContain("点赞 未提供");
  expect(await card.innerText()).toContain("已有候选选题");
  await card.getByRole("button", { name: "标记已读", exact: true }).click();
  await card.getByRole("button", { name: "标为未读", exact: true }).waitFor();
  await page.getByRole("link", { name: "未读 / 有更新", exact: true }).click();
  await page.waitForURL(url => url.searchParams.get("view") === "unread");
  await page.getByRole("heading", { name: "没有发布时间的作品", exact: true }).waitFor();
  expect(await page.getByRole("heading", { name: "普通作品也能研究", exact: true }).count()).toBe(0);
  await page.goto(origin + "/research/works?days=3");
  await page.getByRole("heading", { name: "普通作品也能研究", exact: true }).waitFor();
  expect(await page.getByRole("heading", { name: "没有发布时间的作品", exact: true }).count()).toBe(0);
  await page.screenshot({ path: resolve(output, "works-queue.png"), fullPage: true });
  expect(await creativeSnapshot()).toBe(before); expect(assistantPosts).toBe(0);
  completed.push("saved-work-queue-real-dates-missing-metrics-unread-adopted"); await page.close();
}, 120000);
