import { randomUUID } from "node:crypto";
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { createRequire } from "node:module";
import { chromium, type Browser, type BrowserContext } from "@playwright/test";
import { afterAll, beforeAll, expect, it, vi } from "vitest";
vi.mock("server-only", () => ({}));
import { db } from "@content-center/db"; import { auth } from "../lib/auth";
const origin = "http://localhost:3030", output = path.resolve(process.cwd(), "../../output/research-news-private-verification/browser");
let browser: Browser, context: BrowserContext, foreign: BrowserContext, userId = "", workspaceId = "", otherId = "";
const sessionIds: string[] = [], checks: string[] = [], pageErrors: string[] = [];
let modelRequests = 0, foreignNetwork = 0;
const req = createRequire(import.meta.url);
const serializeSignedCookie = req(req.resolve("better-call", { paths: [path.dirname(req.resolve("better-auth/cookies"))] })).serializeSignedCookie as (name: string, value: string, secret: string, options: object) => Promise<string>;
async function addTestSession(context: BrowserContext, id: string) {
 const token = randomUUID() + randomUUID();
 const session = await db.session.create({ data: { userId: id, token, activeWorkspaceId: workspaceId, expiresAt: new Date(Date.now() + 30 * 60000), userAgent: "Disposable news browser acceptance" } }); sessionIds.push(session.id);
 const secret = (await auth.$context).secret;
 const signed = await serializeSignedCookie("content-center-release-review.session_token", token, secret, { path: "/", httpOnly: true, sameSite: "lax" });
 const pair = signed.split(";")[0]!, separator = pair.indexOf("=");
 await context.addCookies([{ name: pair.slice(0, separator), value: pair.slice(separator + 1), url: origin }]);
}
beforeAll(async () => {
 if (new URL(process.env.DATABASE_URL!).port !== "55436") throw Error("REVIEW_ONLY_BROWSER");
 await mkdir(output,{recursive:true});
 const target = await db.user.findFirst({ where: { email: "2629194738@qq.com", systemRole: "SYSTEM_ADMIN", disabledAt: null }, select: { id: true } });
 if (!target) throw Error("ISOLATED_EXISTING_ADMIN_REQUIRED"); userId=target.id;
 otherId=(await db.user.create({data:{email:"news-browser-other-"+randomUUID()+"@example.test",name:"Disposable news browser other",systemRole:"SYSTEM_ADMIN"}})).id;
 workspaceId=(await db.workspace.create({data:{name:"Disposable news acceptance",slug:randomUUID(),members:{create:[{userId,role:"OWNER"},{userId:otherId,role:"EDITOR"}]}}})).id;
 browser=await chromium.launch({channel:"msedge",headless:true});
 context=await browser.newContext({viewport:{width:1440,height:1000}}); foreign=await browser.newContext();
 await addTestSession(context,userId); await addTestSession(foreign,otherId);
 context.on("request",request=>{const url=new URL(request.url());if(url.origin!==origin)foreignNetwork++;if(/assistant|generate|\/runs$/.test(url.pathname)&&request.method()!=="GET")modelRequests++;});
},60000);
afterAll(async()=>{
 await context?.close();await foreign?.close();await browser?.close();
 if(sessionIds.length)await db.session.deleteMany({where:{id:{in:sessionIds}}});
 if(workspaceId)await db.workspace.delete({where:{id:workspaceId}});
 if(otherId)await db.user.delete({where:{id:otherId}});
 const cleaned=(!workspaceId||await db.workspace.count({where:{id:workspaceId}})===0)&&await db.session.count({where:{id:{in:sessionIds}}})===0;
 await writeFile(path.join(output,"evidence.json"),JSON.stringify({checks,pageErrors,foreignNetwork,modelRequests,fixtureCleanupVerified:cleaned,formalDatabaseWrites:0,usesRealPassword:false,authentication:"ephemeral signed sessions in isolated 55436 only",screenshots:["workbench-library.png","news-desktop.png","news-mobile.png","news-detail.png","official-daily.png"]},null,2));
 expect(cleaned).toBe(true);await db.$disconnect();
},60000);
it("uses authenticated workbench chrome and actual cached public news",async()=>{
 const anonymous=await browser.newContext();
 expect((await anonymous.request.get(origin+"/api/research/news")).status()).toBe(401);
 await anonymous.close();expect((await foreign.request.get(origin+"/api/research/news")).status()).toBe(403);
 expect((await foreign.request.post(origin+"/api/research/news",{headers:{Origin:origin},data:{action:"PAUSE",paused:true}})).status()).toBe(403);
 checks.push("anonymous401-other-admin403");
 const page=await context.newPage();page.on("pageerror",error=>pageErrors.push(error.message));
 expect((await page.goto(origin+"/library"))?.status()).toBe(200);await page.screenshot({path:path.join(output,"workbench-library.png"),fullPage:true});
 expect((await page.goto(origin+"/research"))?.status()).toBe(200);await page.getByTestId("research-news").waitFor();
 const publicModel = await (await context.request.get(origin+"/api/research/news")).json();
 const expectedNews = publicModel.items.filter((item: { category: string; publishedAt: string | null }) => ["ai-models", "ai-products", "industry"].includes(item.category) && (!item.publishedAt || Date.parse(item.publishedAt) >= Date.now() - 7 * 86400000)).length;
 const expectedProducts = publicModel.items.filter((item: { category: string; publishedAt: string | null }) => item.category === "ai-products" && (!item.publishedAt || Date.parse(item.publishedAt) >= Date.now() - 7 * 86400000)).length;
 const unknownProducts = publicModel.items.filter((item: { category: string; publishedAt: string | null }) => item.category === "ai-products" && !item.publishedAt).length;
 expect(expectedNews).toBeGreaterThan(0);
 await page.screenshot({path:path.join(output,"news-desktop.png"),fullPage:true});
 expect(await page.locator(".research-news-item").count()).toBeGreaterThan(0);
 const tokens=await page.evaluate(()=>({app:getComputedStyle(document.documentElement).getPropertyValue("--accent").trim(),research:getComputedStyle(document.querySelector(".research-center")!).getPropertyValue("--research-accent").trim(),font:getComputedStyle(document.querySelector(".research-news-page")!).fontFamily}));
 expect(tokens.research).toBe(tokens.app);expect(tokens.font).toContain("Microsoft YaHei");checks.push("same-workbench-tokens-and-chrome");
 await page.getByRole("button",{name:"近 7 天",exact:true}).click();expect(await page.locator(".research-news-item").count()).toBe(expectedNews);checks.push("actual-current-news-derived-from-cache");
 await page.getByLabel("搜索资讯或来源公司关键词").fill("unlikely-no-result-123");await page.getByRole("button",{name:"搜索",exact:true}).click();expect(await page.locator(".research-news-item").count()).toBe(0);
 await page.getByRole("button",{name:"清除筛选",exact:true}).click();expect(await page.locator(".research-news-item").count()).toBe(expectedNews);checks.push("filter-empty-clear");
 await page.getByLabel("资讯类别").selectOption("ai-products");expect(await page.locator(".research-news-item").count()).toBe(expectedProducts);
 await page.getByRole("button",{name:"日期待确认",exact:true}).click();expect(await page.locator(".research-news-item").count()).toBe(unknownProducts);checks.push("unknown-publication-not-today");
 await page.getByRole("button",{name:"清除筛选",exact:true}).click();
 await page.getByLabel("资讯类别").selectOption("ai-products");await page.getByLabel("资讯排序").selectOption("oldest");
 await page.getByLabel("搜索资讯或来源公司关键词").fill("unlikely-no-result-url");
 await page.getByRole("button",{name:"搜索",exact:true}).click();
 await expect.poll(()=>new URL(page.url()).searchParams.get("q")).toBe("unlikely-no-result-url");
 await page.reload();await page.getByTestId("research-news").waitFor();
 await expect.poll(async()=>page.getByLabel("搜索资讯或来源公司关键词").inputValue()).toBe("unlikely-no-result-url");
 expect(await page.getByLabel("资讯类别").inputValue()).toBe("ai-products");expect(await page.getByLabel("资讯排序").inputValue()).toBe("oldest");
 expect(await page.locator(".research-news-item").count()).toBe(0);
 await page.getByRole("button",{name:"清除关键词",exact:true}).click();
 await expect.poll(()=>page.locator(".research-news-item").count()).toBe(expectedProducts);
 expect(new URL(page.url()).searchParams.get("category")).toBe("ai-products");
 await page.getByRole("button",{name:"清除类别",exact:true}).click();
 await page.getByRole("button",{name:"清除筛选",exact:true}).click();checks.push("submitted-search-url-reload-sort-category-chips");
 const first=page.locator(".research-news-item").nth(Math.min(5, expectedNews - 1));const title=await first.locator(".research-news-title").innerText();
 const readBefore=(await (await context.request.get(origin+"/api/research/news")).json()).preferences.filter((x:{read:boolean})=>x.read).length;
 const opener=first.locator(".research-news-title");await opener.scrollIntoViewIfNeeded();
 const scrollBefore=await page.evaluate(()=>({window:window.scrollY,panes:Array.from(document.querySelectorAll("main,.research-main-pane")).map(el=>el.scrollTop)}));
 const filtersBefore=new URL(page.url()).search;
 await opener.click();await page.getByRole("dialog").waitFor();
 await page.screenshot({path:path.join(output,"news-detail.png"),fullPage:false});expect(await page.getByRole("dialog").innerText()).toContain(title);
 await page.keyboard.press("Escape");expect(await page.getByRole("dialog").isVisible()).toBe(false);expect(await opener.evaluate(el=>el===document.activeElement)).toBe(true);expect(await page.evaluate(()=>({window:window.scrollY,panes:Array.from(document.querySelectorAll("main,.research-main-pane")).map(el=>el.scrollTop)}))).toEqual(scrollBefore);
 expect(new URL(page.url()).search).toBe(filtersBefore);checks.push("detail-scroll-url-and-focus-return");
 await expect.poll(async()=>{const json=await(await context.request.get(origin+"/api/research/news")).json();return json.preferences.filter((x:{read:boolean})=>x.read).length;}).toBe(readBefore+1);
 await first.getByRole("button",{name:"收藏",exact:true}).click();await first.getByRole("button",{name:"已收藏",exact:true}).waitFor();
 await first.getByRole("button",{name:"稍后读",exact:true}).click();await first.getByRole("button",{name:"已稍后读",exact:true}).waitFor();
 await page.reload();await page.getByLabel("个人阅读状态").selectOption("favorites");expect(await page.locator(".research-news-item").count()).toBe(1);
 expect(await page.locator(".research-news-item").innerText()).toContain(title);checks.push("real-personal-preferences-persist-after-reload");
 await page.getByRole("button",{name:"清除筛选",exact:true}).click();await page.setViewportSize({width:390,height:844});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2)).toBe(true);
 const filterButton=page.getByRole("button",{name:"筛选",exact:true});await filterButton.click();
 const drawer=page.getByRole("dialog",{name:"筛选资讯"});await drawer.waitFor();
 await drawer.getByLabel("资讯类别").selectOption("ai-products");await drawer.getByLabel("资讯排序").selectOption("oldest");
 await page.keyboard.press("Tab");expect(await drawer.evaluate(el=>el.contains(document.activeElement))).toBe(true);
 await page.screenshot({path:path.join(output,"news-mobile-filters.png"),fullPage:false});
 await page.keyboard.press("Escape");expect(await drawer.isVisible()).toBe(false);expect(await filterButton.evaluate(el=>el===document.activeElement)).toBe(true);
 expect(new URL(page.url()).searchParams.get("category")).toBe("ai-products");checks.push("mobile-filter-dialog-selection-tab-escape-focus");
 await page.getByRole("button",{name:"清除筛选",exact:true}).click();
 await page.screenshot({path:path.join(output,"news-mobile.png"),fullPage:false});await page.locator(".research-news-title").first().click();await page.screenshot({path:path.join(output,"news-mobile-detail.png"),fullPage:false});await page.keyboard.press("Escape");checks.push("390-mobile-reading-dialog-no-overflow");
 await page.getByRole("button",{name:"每日早报",exact:true}).click();await page.getByText(/官方收录窗口/).waitFor();
 expect(await page.getByLabel("官方日刊日期").locator("option").count()).toBe(publicModel.dailies.length);
 await page.screenshot({path:path.join(output,"official-daily.png"),fullPage:true});checks.push("real-daily-window-and-current-history-index");
 const realToc=page.getByRole("navigation",{name:"日刊目录"});
 expect(await realToc.locator("a").count()).toBeGreaterThan(0);
 await realToc.locator("a").first().click();expect(new URL(page.url()).hash).toContain("#daily-");
 const anchor=await realToc.locator("a").first().getAttribute("href");
 expect(await page.locator(anchor!).count()).toBe(1);checks.push("real-report-directory-anchor");
 await page.getByLabel("官方日刊日期").selectOption("2026-10-05");
 expect(new URL(page.url()).hash).toBe("");await page.getByText(/官方收录窗口/).waitFor();expect(await page.locator(".research-news-daily-body>header").innerText()).toContain("2026-10-05");expect(await page.getByText("本期暂无条目，日期和官方统计窗口保留如上。").count()).toBe(1);checks.push("real-empty-daily-keeps-date-window-and-navigation");
 const editionBefore=await page.getByLabel("官方日刊日期").inputValue();
 await page.getByRole("button",{name:"上一期",exact:true}).click();
 await expect.poll(async()=>page.getByLabel("官方日刊日期").inputValue()).not.toBe(editionBefore);
 await page.getByRole("button",{name:"下一期",exact:true}).click();expect(await page.getByLabel("官方日刊日期").inputValue()).toBe(editionBefore);
 const history=page.locator(".research-news-daily-body .research-news-history");await history.locator(":scope>summary").click();
 const month=history.locator("details").first();await month.locator("summary").click();expect(await month.locator("button").first().isVisible()).toBe(true);
 await history.locator(":scope>summary").click();
 const toc=page.getByRole("navigation",{name:"日刊目录"});if(await toc.count()){await toc.locator("a").first().click();expect(new URL(page.url()).hash).toContain("#daily-");}
 checks.push("daily-adjacent-editions-month-collapse-toc");
 await page.setViewportSize({width:1440,height:1000});
 await page.screenshot({path:path.join(output,"daily-desktop-reading.png"),fullPage:true});
 await page.setViewportSize({width:1920,height:1080});
 const reading=await page.locator(".research-news-daily").evaluate(el=>({container:el.getBoundingClientRect().width,body:el.querySelector(".research-news-daily-body")!.getBoundingClientRect().width,history:getComputedStyle(el.querySelector(".research-news-history-aside")!).display}));
 if(reading.container>=1040){expect(reading.history).toBe("block");expect(reading.body).toBeGreaterThanOrEqual(680);}
 await page.screenshot({path:path.join(output,"daily-wide-history.png"),fullPage:true});checks.push("responsive-history-rail-reading-width");
 await page.setViewportSize({width:1440,height:1000});
 await page.route("**/api/research/news",route=>route.fulfill({status:503,contentType:"application/json",body:JSON.stringify({error:{message:"验证失败状态"}})}));
 await page.getByRole("button",{name:"检查资讯更新"}).click();await page.locator(".research-news-page [role=alert]").waitFor();expect(await page.locator(".research-news-daily-body>header").count()).toBe(1);checks.push("failure-retains-reading-content");
 await page.unroute("**/api/research/news");
 expect(modelRequests).toBe(0);expect(foreignNetwork).toBe(0);expect(pageErrors).toEqual([]);checks.push("no-browser-upstream-or-model-calls");
 await page.close();
},180000);
