import { randomUUID } from 'node:crypto';
import { createElement } from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
import { Card } from '@content-center/ui';
import { mkdir, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { chromium, type Browser, type BrowserContext } from '@playwright/test';
import { afterAll, beforeAll, expect, it, vi } from 'vitest';
vi.mock('server-only', () => ({}));
import { db } from '@content-center/db';
import { auth } from '../lib/auth';
import { businessDay, dayOffset } from '../server/video-operations/policy';

const origin = 'http://localhost:3022';
const output = process.env.VIDEO_ANALYTICS_EVIDENCE_DIR ?? resolve(process.cwd(), '../../output/video-analytics-qa');
let userId = '', workspaceId = '', browser: Browser | undefined, context: BrowserContext | undefined;
const runtimeErrors: string[] = [], checks: string[] = [];
beforeAll(async () => {
  if (process.env.ENVIRONMENT_ID !== 'LOCAL_REVIEW' || new URL(process.env.DATABASE_URL!).port !== '55438') throw Error('ISOLATED_REVIEW_REQUIRED');
  await mkdir(output, { recursive: true });
  const email = `video-browser-${randomUUID()}@example.test`, password = `disposable-${randomUUID()}`;
  const result = await auth.api.signUpEmail({ body: { name: '临时数据中台验收', email, password } });
  userId = result.user.id;
  workspaceId = (await db.workspace.create({ data: { name: '临时验收工作空间', slug: `video-browser-${randomUUID()}`, members: { create: { userId, role: 'OWNER' } } } })).id;
  const account = await db.videoAccount.create({ data: { workspaceId, handle: '真实验收账号', externalId: randomUUID() } });
  await db.videoDailyMetric.create({ data: { workspaceId, accountId: account.id, day: new Date(businessDay() + 'T00:00:00Z'), plays: 1234, likes: 40, comments: 5, saves: 10, shares: 3, netFollowers: -2, negativeComments: 0, observedAt: new Date(), source: 'MANUAL', updatedById: userId } });
  const response = await auth.api.signInEmail({ body: { email, password }, asResponse: true });
  expect(response.ok).toBe(true);
  browser = await chromium.launch({ channel: 'msedge', headless: true });
  context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, acceptDownloads: true });
  await context.grantPermissions(['clipboard-read', 'clipboard-write'], { origin });
  await context.addCookies(response.headers.getSetCookie().map(value => { const pair = value.split(';')[0]!, split = pair.indexOf('='); return { name: pair.slice(0, split), value: pair.slice(split + 1), url: origin }; }));
}, 90_000);

afterAll(async () => {
  await context?.close(); await browser?.close();
  if (workspaceId) {
    await db.videoDailyMetric.deleteMany({ where: { workspaceId } });
    await db.videoAccount.deleteMany({ where: { workspaceId } });
    await db.workspace.deleteMany({ where: { id: workspaceId } });
  }
  if (userId) await db.user.deleteMany({ where: { id: userId } });
  await writeFile(resolve(output, '数据中台浏览器验收.json'), JSON.stringify({ checks, runtimeErrors, fixtureCleanupVerified: userId ? await db.user.count({ where: { id: userId } }) === 0 : true, usesRealUserPassword: false, paidModelCalls: 0 }, null, 2));
  await db.$disconnect();
}, 30_000);

it('keeps real account records distinct from demo analytics and renders honest missing states', async () => {
  const page = await context!.newPage(); page.setDefaultTimeout(20000);
  page.on('pageerror', e => runtimeErrors.push(e.message));
  const response = await page.goto(origin + '/short-video', { waitUntil: 'load', timeout: 60000 });
  expect(response?.status()).toBe(200);
  await page.locator('.va-metrics strong').first().waitFor();
  expect(await page.locator('.va-metrics strong').first().textContent()).toBe('1,234');
  expect(await page.getByText('尚未接入粉丝画像', { exact: true }).count()).toBe(1);
  expect(await page.getByText('暂无作品级表现数据', { exact: true }).count()).toBe(1);
  await page.screenshot({ path: resolve(output, '数据中台-真实数据.png'), fullPage: true });
  await page.getByRole('button', { name: '账号矩阵', exact: true }).click();
  await page.locator('.video-account-row strong').filter({ hasText: '真实验收账号' }).waitFor();
  expect(await page.getByText('真实运营管理 · 使用现有业务流程').count()).toBe(1);
  await page.getByRole('button', { name: '添加账号', exact: true }).click();
  const managementDialog = page.getByRole('dialog');
  expect(await managementDialog.locator('h2').evaluate(el => getComputedStyle(el).fontSize)).toBe('16px');
  expect(await managementDialog.evaluate(el => getComputedStyle(el).padding)).toBe('20px');
  await page.keyboard.press('Escape');
  await page.close(); checks.push('真实指标与缺失状态、既有账号管理');
}, 90_000);

it('renders the redesigned cockpit at the post-login home route', async () => {
  const page = await context!.newPage();
  page.on('pageerror', e => runtimeErrors.push(e.message));
  const response = await page.goto(origin + '/home', { waitUntil: 'load', timeout: 60000 });
  expect(response?.status()).toBe(200);
  await page.locator('.va-metrics strong').first().waitFor();
  expect(await page.locator('.va-metrics strong').first().textContent()).toMatch(/[0-9]/);
  expect(await page.locator('.va-status').count()).toBe(0);
  expect(await page.locator('.va-source-line').count()).toBe(0);
  expect(await page.locator('.va-workspace').innerText()).not.toMatch(/演示|真实记录|模拟|预置样例/);
  expect(await page.getByRole('button', { name: '粉丝画像', exact: true }).count()).toBe(1);
  expect(await page.locator('[data-surface="console-dark"]').evaluate(el => getComputedStyle(el).getPropertyValue('--surface').trim())).toBe('#111e32');
  expect(await page.locator('.va-profile-head strong').count()).toBe(1);
  await page.screenshot({ path: resolve(output, '登录首页-新版驾驶舱.png'), fullPage: true });
  await page.close(); checks.push('登录默认首页使用新版驾驶舱、直接展示完整数据、无数据来源备注');
}, 90_000);

it('filters demo consistently, opens details, exports data and hands off review without database writes', async () => {
  const before = await db.videoAccount.count({ where: { workspaceId } });
  const page = await context!.newPage(); page.setDefaultTimeout(20000);
  page.on('pageerror', e => runtimeErrors.push(e.message));
  const response = await page.goto(origin + '/short-video?demo=1', { waitUntil: 'load', timeout: 60000 });
  expect(response?.status()).toBe(200);
  await page.locator('.va-metrics strong').first().waitFor();
  expect(await page.locator('[data-surface="console-dark"]').evaluate(el => getComputedStyle(el).getPropertyValue('--surface').trim())).toBe('#111e32');
  const profileBox = await page.locator('.va-audience').boundingBox();
  const accountBox = await page.locator('.va-account-panel').boundingBox();
  expect(Math.abs(profileBox!.y - accountBox!.y)).toBeLessThan(2);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: resolve(output, '数据中台-深色概览.png'), fullPage: true });
  await page.getByLabel('平台筛选', { exact: true }).selectOption('XIAOHONGSHU');
  expect(await page.getByLabel('账号筛选', { exact: true }).locator('option').count()).toBe(3);
  await page.getByLabel('账号筛选', { exact: true }).selectOption('demo-xhs-2');
  await page.getByLabel('时间范围', { exact: true }).selectOption('7');
  expect(await page.locator('.va-account').count()).toBe(1);
  expect(await page.locator('.va-profile-head strong').textContent()).toBe('8,640');
  await page.getByRole('button', { name: '作品表现', exact: true }).click();
  expect(await page.locator('.va-work-table tbody tr').count()).toBe(4);
  await page.getByRole('button', { name: '涨粉榜', exact: true }).click();
  await page.locator('.va-work-title').first().click();
  await page.getByRole('dialog').waitFor();
  expect(await page.locator('.va-detail-metrics article').count()).toBe(6);
  await page.screenshot({ path: resolve(output, '数据中台-作品详情.png'), fullPage: true });
  await page.keyboard.press('Escape');
  expect(await page.getByRole('dialog').count()).toBe(0);
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('button', { name: '导出作品', exact: true }).click();
  const download = await downloadPromise;
  expect(download.suggestedFilename()).toContain('演示');
  await page.getByRole('button', { name: '粉丝画像', exact: true }).click();
  expect(await page.getByRole('heading', { name: '性别分布' }).count()).toBe(1);
  await page.getByRole('button', { name: 'AI复盘', exact: true }).click();
  await page.getByRole('button', { name: '复制复盘', exact: true }).click();
  await page.getByRole('status').waitFor();
  const clipboard = await page.evaluate(() => navigator.clipboard.readText());
  expect(clipboard).toContain('演示数据，不能作为真实经营依据');
  expect(clipboard).toContain('启航教育 · 课堂记录');
  expect(await db.videoAccount.count({ where: { workspaceId } })).toBe(before);
  await page.close(); checks.push('平台/账号/周期联动、排行、详情、导出、画像、复盘交接、演示隔离');
}, 90_000);

it('keeps shared cards consistent across dark routes, preserves the light theme and maps data series colors', async () => {
  const page = await context!.newPage();
  const lightMarkup = renderToStaticMarkup(createElement(Card, { id: 'light-theme-probe' }, 'Light Card'));
  await page.goto(origin + '/projects', { waitUntil: 'load', timeout: 60000 });
  await page.evaluate(markup => { const host = document.createElement('div'); host.innerHTML = markup; document.body.append(host); }, lightMarkup);
  const baseline = await page.locator('#light-theme-probe').evaluate(el => {
    const style = getComputedStyle(el);
    return { surface: style.getPropertyValue('--surface').trim(), background: style.backgroundColor, border: style.borderTopColor, radius: style.borderRadius };
  });
  const baselineAccent = await page.locator('body').evaluate(el => getComputedStyle(el).getPropertyValue('--accent').trim());
  expect(await page.locator('#light-theme-probe').evaluate(el => getComputedStyle(el).backgroundImage)).toContain('linear-gradient');
  expect(baseline.radius).toBe('14px');
  expect(baseline.surface).toBe('#111e32');
  await page.locator('body').evaluate(el => el.removeAttribute('data-theme'));
  const lightSurface = await page.locator('#light-theme-probe').evaluate(el => getComputedStyle(el).getPropertyValue('--surface').trim());
  expect(lightSurface).not.toBe(baseline.surface);
  expect(await page.locator('#light-theme-probe').evaluate(el => getComputedStyle(el).borderRadius)).toBe('14px');
  await page.locator('body').evaluate(el => el.setAttribute('data-theme', 'black-titanium'));
  await page.goto(origin + '/short-video?demo=1', { waitUntil: 'load', timeout: 60000 });
  await page.evaluate(markup => { const host = document.createElement('div'); host.id = 'light-theme-probe-host'; host.innerHTML = markup; document.body.append(host); }, lightMarkup);
  const outside = await page.locator('#light-theme-probe').evaluate(el => {
    const style = getComputedStyle(el);
    return { surface: style.getPropertyValue('--surface').trim(), background: style.backgroundColor, border: style.borderTopColor, radius: style.borderRadius };
  });
  expect(outside).toEqual(baseline);
  expect(await page.locator('body').evaluate(el => getComputedStyle(el).getPropertyValue('--accent').trim())).toBe(baselineAccent);
  const kpi = page.locator('.console-kpi').first();
  const material = await kpi.evaluate(el => ({ padding: getComputedStyle(el).padding, radius: getComputedStyle(el).borderRadius, image: getComputedStyle(el).backgroundImage }));
  expect(material.padding).toBe('24px'); expect(material.radius).toBe('14px'); expect(material.image).toContain('linear-gradient');
  expect(await page.locator('.va-panel').first().evaluate(el => getComputedStyle(el).backgroundImage)).toContain('linear-gradient');
  await kpi.hover(); await page.waitForTimeout(200);
  expect(await kpi.evaluate(el => getComputedStyle(el).transform)).toBe('matrix(1, 0, 0, 1, 0, -2)');
  await page.emulateMedia({ reducedMotion: 'reduce' });
  expect(await kpi.evaluate(el => ({ transform: getComputedStyle(el).transform, transition: getComputedStyle(el).transitionDuration }))).toEqual({ transform: 'none', transition: '0s' });
  await page.locator('.va-metrics').screenshot({ path: resolve(output, '驾驶舱KPI-最小切片.png') });
  await page.emulateMedia({ reducedMotion: 'no-preference' });
  const numberStyle = await kpi.locator('strong').evaluate(el => ({ size: parseFloat(getComputedStyle(el).fontSize), weight: getComputedStyle(el).fontWeight, numeric: getComputedStyle(el).fontVariantNumeric }));
  expect(numberStyle.size).toBeGreaterThanOrEqual(28); expect(numberStyle.size).toBeLessThanOrEqual(42);
  expect(numberStyle.weight).toBe('600'); expect(numberStyle.numeric).toBe('tabular-nums');
  expect(await kpi.locator('.console-kpi-unit').evaluate(el => getComputedStyle(el).fontSize)).toBe('16px');
  expect(await kpi.locator('.console-card-title > span').first().isVisible()).toBe(false);
  const invalidTextSizes = await page.locator('[data-surface="console-dark"]').evaluate(root => [...root.querySelectorAll('h1,h2,h3,p,span,strong,small,b,th,td,button,select')].filter(el => !el.children.length && el.textContent?.trim()).map(el => ({ text: el.textContent, size: getComputedStyle(el).fontSize })).filter(item => parseFloat(item.size) < 12 || parseFloat(item.size) > 42));
  expect(invalidTextSizes).toEqual([]);
  const trend = page.locator('.va-trend');
  expect(await trend.locator('.va-series-line').evaluate(el => getComputedStyle(el).stroke)).toBe('rgb(45, 212, 239)');
  await trend.getByRole('button', { name: '互动', exact: true }).click();
  expect(await trend.locator('.va-series-line').evaluate(el => getComputedStyle(el).stroke)).toBe('rgb(137, 119, 248)');
  await trend.getByRole('button', { name: '净增粉丝', exact: true }).click();
  expect(await trend.locator('.va-series-line').evaluate(el => getComputedStyle(el).stroke)).toBe('rgb(57, 205, 177)');
  await page.locator('#light-theme-probe-host').evaluate(el => el.remove());
  await page.locator('.va-work-title').first().click();
  expect(await page.getByRole('dialog').evaluate(el => getComputedStyle(el).getPropertyValue('--surface').trim())).toBe('#111e32');
  await page.keyboard.press('Escape');
  await page.goto(origin + '/projects', { waitUntil: 'load', timeout: 60000 });
  expect(await page.locator('[data-surface="console-dark"]').count()).toBe(0);
  expect(await page.locator('body').evaluate(el => getComputedStyle(el).getPropertyValue('--surface').trim())).toBe(baseline.surface);
  await page.close(); checks.push('全站深色Card一致、原浅色主题保留、KPI排版间距、三条数据序列色、弹窗继承');
}, 90_000);

it('supports narrow screens and simulated updates without silent real-data fallback', async () => {
  const page = await context!.newPage(); page.setDefaultTimeout(20000);
  page.on('pageerror', e => runtimeErrors.push(e.message));
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto(origin + '/short-video?demo=1', { waitUntil: 'load', timeout: 60000 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  const before = await page.locator('.va-metrics strong').first().textContent();
  await page.getByRole('button', { name: '模拟更新', exact: true }).click();
  expect(await page.locator('.va-metrics strong').first().textContent()).not.toBe(before);
  await page.screenshot({ path: resolve(output, '数据中台-移动布局.png'), fullPage: true });
  await page.route('**/api/video-data?*', route => route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ message: '验收用同步失败' }) }));
  await page.getByRole('button', { name: '返回真实数据', exact: true }).click();
  await page.locator('.va-error').waitFor();
  expect(await page.locator('.va-status').textContent()).toBe('真实记录');
  expect(await page.locator('.va-metrics').count()).toBe(0);
  await page.close(); expect(runtimeErrors).toEqual([]); checks.push('窄屏无溢出、模拟更新、失败不自动填充样例、无运行时错误');
}, 90_000);

it('paginates records, validates custom dates and filters task platforms with equal controls', async () => {
  const today = businessDay();
  const dy = await db.videoAccount.create({ data: { workspaceId, handle: '分页验收抖音', externalId: randomUUID(), platform: 'DOUYIN' } });
  const xhs = await db.videoAccount.create({ data: { workspaceId, handle: '分页验收小红书', externalId: randomUUID(), platform: 'XIAOHONGSHU' } });
  const page = await context!.newPage(); page.setDefaultTimeout(20000);
  page.on('pageerror', e => runtimeErrors.push(e.message));
  try {
    await db.videoDailyMetric.createMany({ data: Array.from({ length: 25 }, (_, i) => ({ workspaceId, accountId: dy.id, day: new Date(dayOffset(today, -i) + 'T00:00:00Z'), plays: 100 + i, likes: 1, comments: 0, saves: 0, shares: 0, netFollowers: 0, negativeComments: 0, observedAt: new Date(), source: 'MANUAL', updatedById: userId })) });
    await db.videoDailyMetric.create({ data: { workspaceId, accountId: xhs.id, day: new Date(today + 'T00:00:00Z'), plays: 999, likes: 0, comments: 0, saves: 0, shares: 0, netFollowers: 0, negativeComments: 0, observedAt: new Date(), source: 'MANUAL', updatedById: userId } });
    await db.videoTask.create({ data: { workspaceId, accountId: xhs.id, createdById: userId, assigneeId: userId, title: '小红书筛选验收任务', kind: 'EDIT', dueAt: new Date(), status: 'TODO' } });
    await page.goto(origin + '/home', { waitUntil: 'load' });
    await page.getByRole('button', { name: '数据记录', exact: true }).click();
    await page.getByLabel('数据账号筛选', { exact: true }).selectOption(dy.id);
    await page.waitForFunction(() => document.querySelector('.video-pagination')?.textContent?.includes('共 25 条'));
    expect(await page.locator('.video-records tbody tr').count()).toBe(20);
    await page.getByRole('button', { name: '下一页', exact: true }).click();
    expect(await page.locator('.video-records tbody tr').count()).toBe(5);
    expect(await page.getByRole('button', { name: '下一页', exact: true }).isDisabled()).toBe(true);
    const heights = await page.locator('.video-filter-pill').evaluateAll(elements => elements.map(e => e.getBoundingClientRect().height));
    expect(new Set(heights).size).toBe(1);
    await page.getByLabel('趋势时间范围').selectOption('custom');
    const dialog = page.getByRole('dialog', { name: '自定义时间' });
    for (const viewport of [{ width: 1440, height: 1000 }, { width: 2048, height: 1022 }, { width: 390, height: 844 }, { width: 844, height: 300 }]) {
      await page.setViewportSize(viewport);
      const box = await dialog.boundingBox();
      expect(box).not.toBeNull();
      expect(Math.abs(box!.x + box!.width / 2 - viewport.width / 2)).toBeLessThan(2);
      expect(Math.abs(box!.y + box!.height / 2 - viewport.height / 2)).toBeLessThan(2);
      expect(box!.height).toBeLessThanOrEqual(viewport.height - 32);
    }
    await page.setViewportSize({ width: 1440, height: 1000 });
    await page.screenshot({ path: resolve(output, '自定义时间-居中弹窗.png') });
    expect(await dialog.getByLabel('结束日期').getAttribute('max')).toBe(today);
    await dialog.getByLabel('结束日期').fill(dayOffset(today, 1));
    expect(await dialog.getByLabel('结束日期').evaluate((input: HTMLInputElement) => input.validity.rangeOverflow)).toBe(true);
    await dialog.getByRole('button', { name: '应用' }).click();
    expect(await dialog.isVisible()).toBe(true);
    await dialog.getByLabel('结束日期').fill(dayOffset(today, -5));
    await dialog.getByLabel('开始日期').fill(dayOffset(today, -10));
    await dialog.getByRole('button', { name: '应用' }).click();
    await page.waitForFunction(() => document.querySelector('.video-pagination')?.textContent?.includes('共 6 条'));
    expect(await page.locator('.video-records tbody tr').count()).toBe(6);
    expect(await page.locator('.video-pagination').textContent()).toContain('第 1/1 页');
    await page.getByLabel('趋势时间范围').selectOption('30');
    await page.getByLabel('运营平台筛选').selectOption('XIAOHONGSHU');
    await page.waitForFunction(() => document.querySelector('.video-pagination')?.textContent?.includes('共 1 条'));
    expect(await page.locator('.video-records tbody').textContent()).toContain('分页验收小红书');
    expect(await page.getByLabel('数据账号筛选').inputValue()).toBe('');
    await page.screenshot({ path: resolve(output, '数据记录-分页及平台筛选.png'), fullPage: true });
    const bad = await context!.request.get(origin + '/api/video-data?start=' + today + '&end=' + dayOffset(today, 1));
    expect(bad.status()).toBe(400);
    await page.goto(origin + '/short-video/tasks', { waitUntil: 'load' });
    await page.getByLabel('运营平台筛选').selectOption('XIAOHONGSHU');
    await page.getByText('小红书筛选验收任务', { exact: true }).waitFor();
    expect(await page.locator('.video-task-row small').textContent()).toContain('小红书');
    expect(await page.locator('.video-task-row small').textContent()).not.toContain('抖音');
    const taskHeights = await page.locator('.video-filter-pill').evaluateAll(elements => elements.map(e => e.getBoundingClientRect().height));
    expect(new Set(taskHeights).size).toBe(1);
    checks.push('每页20条、尾页禁用、日期校验、服务端拒绝未来、平台及任务筛选、控件等高');
  } finally {
    await page.close();
    await db.videoTask.deleteMany({ where: { accountId: { in: [dy.id, xhs.id] } } });
    await db.videoDailyMetric.deleteMany({ where: { accountId: { in: [dy.id, xhs.id] } } });
    await db.videoAccount.deleteMany({ where: { id: { in: [dy.id, xhs.id] } } });
  }
}, 90_000);
