import Link from "next/link";
import { requireWorkspace } from "@/server/access";
import { researchTrendList } from "@/server/research/trends";
import { TrendRefresh } from "@/components/research/trend-refresh";
import { platformLabel, trendTypeLabel } from "@/components/research/research-labels";

type Query = { q?: string; platform?: string; type?: string; state?: string; since?: string; page?: string };
const states: Record<string, string> = { FIRST_SEEN: "首次被本系统观察", RISING: "排名上升", PERSISTING: "持续观察" };
export default async function ResearchTrends({ searchParams }: { searchParams: Promise<Query> }) {
  const { workspace, session, role } = await requireWorkspace(); const query = await searchParams;
  const data = await researchTrendList({ workspaceId: workspace.id, userId: session.user.id }, query);
  const href = (page: number) => { const params = new URLSearchParams(Object.entries(query).filter((entry): entry is [string, string] => typeof entry[1] === "string")); params.set("page", String(page)); return `/research/trends?${params}`; };
  const stateLink = (state: string) => { const params = new URLSearchParams(Object.entries(query).filter((entry): entry is [string, string] => typeof entry[1] === "string")); params.delete("page"); if (state) params.set("state", state); else params.delete("state"); return `/research/trends?${params}`; };
  return <div><header className="research-page-heading"><div><span className="research-eyebrow">研究中心 / 趋势</span><h1>趋势</h1><p>看看关注的话题发生了什么变化，再决定哪些值得深入研究。</p></div><details className="research-action-disclosure"><summary>更新榜单</summary><TrendRefresh canWrite={role !== "VIEWER"} platform={query.platform || "ALL"} type={query.type || "HOT"} initialKeyword={query.q} /></details></header>
    <form className="research-toolbar research-filters"><input type="hidden" name="state" value={query.state || ""} /><label>查找趋势<input type="search" name="q" defaultValue={query.q} placeholder="话题或关键词" /></label><label>平台<select name="platform" defaultValue={query.platform || ""}><option value="">全部平台</option><option value="DOUYIN">抖音</option><option value="XIAOHONGSHU">小红书</option><option value="GLOBAL">全网</option></select></label><label>榜单<select name="type" defaultValue={query.type || ""}><option value="">全部榜单</option><option value="HOT">热门</option><option value="SURGING">上升</option><option value="DARK_HORSE">黑马</option></select></label><label>观察时间始于<input type="date" name="since" defaultValue={query.since} /></label><button type="submit">筛选</button></form>
    <nav className="research-filter-states" aria-label="趋势观察状态">{[["", "全部"], ["RISING", "排名上升"], ["FIRST_SEEN", "新观察"], ["PERSISTING", "持续观察"], ["FOLLOWED", "我关注的"]].map(([value, label]) => <Link href={stateLink(value!)} key={value} aria-current={(query.state || "") === value ? "page" : undefined}>{label}</Link>)}</nav>
    {data.items.length ? <section className="research-observation-stats" aria-label="当前页趋势概览"><div><strong>{data.items.length}</strong><span>当前页话题</span></div><div><strong>{data.items.filter(item => item.rankDelta !== null && item.rankDelta > 0).length}</strong><span>排名上升</span></div><div><strong>{data.items.filter(item => item.state === "FIRST_SEEN").length}</strong><span>首次观察</span></div><div><strong>{data.items.filter(item => item.followed).length}</strong><span>已关注</span></div></section> : null}
    {data.items.length ? <div className="research-table-scroll"><table aria-label="趋势列表"><thead><tr><th className="is-number">排名</th><th>趋势</th><th>平台 / 榜单</th><th className="is-number">排名变化</th><th>观察状态</th><th>最近观察</th><th>关注</th></tr></thead><tbody>{data.items.map(item => <tr key={item.stableKey}><td className="is-number"><strong>{item.rank ?? "—"}</strong></td><td><Link href={`/research/trends/${item.stableKey}`}><h2 className="research-cell-title">{item.title}</h2></Link></td><td className="is-muted">{platformLabel[item.platform]} · {trendTypeLabel[item.trendType]}</td><td className="is-number"><span className={`research-delta ${item.rankDelta !== null && item.rankDelta < 0 ? "is-down" : ""}`}>{item.rankDelta === null ? "—" : item.rankDelta > 0 ? `↑ ${item.rankDelta}` : item.rankDelta < 0 ? `↓ ${-item.rankDelta}` : "持平"}</span></td><td className="is-muted">{states[item.state]}</td><td className="is-muted">{item.observedAt.toLocaleString("zh-CN", { timeZone: "Asia/Shanghai", year: "numeric", month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit" })}</td><td className="is-muted">{item.followed ? "已关注" : "—"}</td></tr>)}</tbody></table></div> : <div className="research-center-empty"><h2>{query.q || query.platform || query.type || query.state || query.since ? "没有匹配的趋势" : "还没有保存的趋势"}</h2><p>从“更新榜单”主动获取数据，或调整筛选查看历史记录。更新失败也不会影响已有记录。</p><Link className="research-button" href="/research/trends">查看全部</Link></div>}
    <p className="research-caption" style={{ marginTop: 14 }}>共 {data.count} 条 · 排名变化只比较同平台、同榜单的先后观察。“新观察”表示我们第一次记录，不代表事件刚刚发生。</p>
    {data.pages > 1 ? <nav className="research-pagination" aria-label="趋势分页">{data.page > 1 ? <Link href={href(data.page - 1)}>上一页</Link> : null}<span>第 {data.page} / {data.pages} 页</span>{data.page < data.pages ? <Link href={href(data.page + 1)}>下一页</Link> : null}</nav> : null}
  </div>;
}
