"use client";

import { Badge, Button } from "@content-center/ui";
import { Plus } from "lucide-react";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { sourcePlatformLabels, sourceTypeLabels } from "@/lib/content-labels";
import type { MaterialAnalysisOutput } from "@/server/material-analysis/schemas";
import { StudioDrawer } from "./studio-drawer";

export type ProjectSource = { role: string; addedAt: string; sourceItem: { id: string; title: string | null; author: string | null; description: string | null; displayName: string; sourcePlatform: string; sourceType: string; status: string; thumbnailUrl: string | null; updatedAt: string; tags: Array<{ id: string; name: string }>; assets: Array<{ id: string; assetType: string; status: string; mimeType: string | null }>; rawText: string | null; transcript: { fullText: string; updatedAt: string } | null; referenceUpdated: boolean; materialAnalysis: { version: number; summary: string | null; keyPoints: string[]; understanding: MaterialAnalysisOutput | null; legacy: boolean } | null } };
type AvailableSource = { id: string; title: string | null; displayName: string; sourcePlatform: string; sourceType: string };

async function request(url: string, method: string, body?: unknown) { const response = await fetch(url, { method, headers: body ? { "content-type": "application/json" } : undefined, body: body ? JSON.stringify(body) : undefined }); const result = await response.json().catch(() => ({})); if (!response.ok) throw new Error(result.message || result.error || "操作失败"); }

export function StudioSources({ projectId, sources, availableSources, editable, manageRequest = 0, onManageRequestHandled, onUse }: { projectId: string; sources: ProjectSource[]; availableSources: AvailableSource[]; editable: boolean; manageRequest?: number; onManageRequestHandled?: () => void; onUse: (content: string) => void }) {
  const router = useRouter();
  const [drawer, setDrawer] = useState<{ type: "SOURCE"; id: string } | { type: "MANAGE" } | null>(null);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const selected = drawer?.type === "SOURCE" ? sources.find(({ sourceItem }) => sourceItem.id === drawer.id) : null;
  useEffect(() => { if (manageRequest && editable) { setDrawer({ type: "MANAGE" }); onManageRequestHandled?.(); } }, [editable, manageRequest, onManageRequestHandled]);
  async function action(work: () => Promise<void>) { setBusy(true); setError(""); try { await work(); setDrawer(null); router.refresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : "操作失败"); } finally { setBusy(false); } }

  return <section aria-labelledby="reference-materials-title">
    <div className="flex items-center justify-between gap-3"><div><h2 id="reference-materials-title" className="font-semibold">当前资料</h2><p className="mt-1 text-xs leading-5 text-[var(--text-secondary)]">只借鉴做法和背景，不照搬对方经历。</p></div><Badge>{sources.length}</Badge></div>
    {sources.some(({ sourceItem }) => sourceItem.referenceUpdated) ? <p className="mt-4 rounded-xl border border-[var(--warning)] p-3 text-sm text-[var(--warning)]">参考资料已更新。你的补充和口播稿不会被自动覆盖。</p> : null}<div className="studio-source-list">{sources.map(({ sourceItem, role }) => <button type="button" key={sourceItem.id} onClick={() => setDrawer({ type: "SOURCE", id: sourceItem.id })}><span className="studio-source-type">{sourceTypeLabels[sourceItem.sourceType] || sourceItem.sourceType}</span><div><p>{sourceItem.displayName}</p><small>{sourcePlatformLabels[sourceItem.sourcePlatform] || sourceItem.sourcePlatform} · {role === "INSPIRATION" ? "外部参考" : "已加入本次创作"}</small></div><Badge>{sourceItem.referenceUpdated ? "已更新" : sourceItem.transcript ? "可使用" : "待转写"}</Badge></button>)}{sources.length === 0 ? <p className="studio-source-empty">尚未添加参考资料，也可以先填写自己的想法。</p> : null}{editable ? <button type="button" onClick={() => setDrawer({ type: "MANAGE" })} className="studio-source-add"><Plus size={16} /> 添加资料</button> : null}</div>
    <StudioDrawer title={selected?.sourceItem.displayName || "参考资料详情"} open={Boolean(selected)} onClose={() => setDrawer(null)}>{selected ? <SourceDetail source={selected} editable={editable} busy={busy} onUse={(content) => { onUse(content); setDrawer(null); }} onRemove={() => action(() => request(`/api/projects/${projectId}/sources/${selected.sourceItem.id}`, "DELETE"))} /> : null}</StudioDrawer>
    <StudioDrawer title="添加参考资料" open={drawer?.type === "MANAGE"} onClose={() => setDrawer(null)} width="max-w-lg"><form className="grid gap-3" action={(formData) => action(() => request(`/api/projects/${projectId}/sources`, "POST", { sourceItemId: String(formData.get("sourceItemId") || ""), role: "REFERENCE" }))}><label className="grid gap-1.5 text-sm">资料<select name="sourceItemId" aria-label="添加资料" required defaultValue="" className="h-10 rounded-[var(--radius)] border bg-[var(--surface)] px-3"><option value="" disabled>选择资料</option>{availableSources.map((source) => <option key={source.id} value={source.id}>{source.displayName} · {sourcePlatformLabels[source.sourcePlatform] || source.sourcePlatform}</option>)}</select></label><Button disabled={busy || availableSources.length === 0}>添加资料</Button></form>{error ? <p role="alert" className="mt-3 text-xs text-[var(--danger)]">{error}</p> : null}</StudioDrawer>
  </section>;
}

function SourceDetail({ source, editable, busy, onUse, onRemove }: { source: ProjectSource; editable: boolean; busy: boolean; onUse: (content: string) => void; onRemove: () => void }) {
  const { sourceItem } = source; const analysis = sourceItem.materialAnalysis; const value = analysis?.understanding;
  return <div className="grid gap-5 text-sm"><div className="flex gap-2"><Badge>{sourcePlatformLabels[sourceItem.sourcePlatform] || sourceItem.sourcePlatform}</Badge><Badge>{sourceItem.transcript ? "已转写" : "未转写"}</Badge></div>
    {value ? <><section><h3 className="font-semibold">它讲了什么</h3><p className="mt-2 leading-6">{value.whatItSays.summary}</p><ul className="mt-2 list-disc space-y-1 pl-5">{value.whatItSays.keyPoints.map((item) => <li key={item}>{item}</li>)}</ul></section><section><h3 className="font-semibold">值得借</h3><div className="mt-2 grid gap-2">{value.reusable.map((item) => <article key={item.content} className="rounded-xl border p-3"><p className="leading-6">{item.content}</p><p className="mt-1 text-xs text-[var(--text-secondary)]">{item.whyUseful}</p>{editable ? <Button variant="ghost" className="mt-2 h-8 px-2 text-xs" onClick={() => onUse(item.content)}>用这个</Button> : null}</article>)}</div></section><Cautions title="不要照搬" items={value.doNotCopy} /><Cautions title="需要确认" items={value.uncertain} /></> : analysis ? <section className="rounded-xl border p-4"><h3 className="font-semibold">旧版整理结果</h3><p className="mt-2 leading-6">{analysis.summary || "暂无摘要"}</p><p className="mt-3 text-xs text-[var(--text-secondary)]">到资料详情页可按新方式重新整理。</p></section> : <p className="text-[var(--text-secondary)]">这条资料还没有整理。</p>}
    <details><summary className="cursor-pointer font-medium">查看文字稿</summary><p className="mt-3 max-h-80 overflow-y-auto whitespace-pre-wrap rounded-xl border p-4 text-xs leading-6 text-[var(--text-secondary)]">{sourceItem.transcript?.fullText || sourceItem.rawText || "暂无可用正文"}</p></details>{editable ? <Button variant="ghost" className="justify-self-start text-[var(--danger)]" disabled={busy} onClick={onRemove}>移出当前创作</Button> : null}</div>;
}
function Cautions({ title, items }: { title: string; items: Array<{ content: string; reason: string }> }) { return <section><h3 className="font-semibold">{title}</h3>{items.length ? <div className="mt-2 grid gap-2">{items.map((item) => <article key={item.content} className="rounded-xl bg-[var(--surface-elevated)] p-3"><p>{item.content}</p><p className="mt-1 text-xs text-[var(--text-secondary)]">{item.reason}</p></article>)}</div> : <p className="mt-2 text-[var(--text-secondary)]">暂无</p>}</section>; }
