import { Badge, Card } from "@content-center/ui";
import { ArrowLeft } from "lucide-react";
import Link from "next/link";
import { notFound } from "next/navigation";
import { RecommendationDetailActions } from "@/components/discovery/recommendation-detail-actions";
import { requireWorkspace } from "@/server/access";
import { getRecommendationItem } from "@/server/discovery/recommendations/service";

const evidenceLabel: Record<string, string> = { TREND: "趋势", BENCHMARK_CONTENT: "对标内容", CONTENT_IDEA: "已有选题", SOURCE_ITEM: "资料", PROJECT: "近期创作", CREATOR_PROFILE: "创作者档案" };

export default async function RecommendationDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const { session, workspace, role } = await requireWorkspace();
  const item = await getRecommendationItem({ workspaceId: workspace.id, userId: session.user.id, itemId: id });
  if (!item) notFound();
  const risks = Array.isArray(item.riskNotes) ? item.riskNotes.filter((risk): risk is string => typeof risk === "string") : [];
  return <div className="mx-auto max-w-5xl"><Link href="/discovery" className="inline-flex items-center gap-2 text-sm text-[var(--text-secondary)]"><ArrowLeft size={15} />返回研究</Link><header className="mt-5"><div className="flex flex-wrap gap-2"><Badge>{item.batch.mode === "AI_ASSISTED" ? "AI 辅助" : "规则线索"}</Badge>{item.recommendedFormat ? <Badge>{item.recommendedFormat}</Badge> : null}</div><h1 className="mt-3 text-3xl font-semibold tracking-tight">{item.title}</h1><p className="mt-3 text-base leading-7 text-[var(--text-secondary)]">{item.coreQuestion}</p></header><div className="mt-7 grid gap-5 lg:grid-cols-[1.4fr_1fr]"><div className="grid gap-5"><Card className="p-5"><h2 className="font-semibold">推荐切口</h2><p className="mt-3 whitespace-pre-wrap text-sm leading-7">{item.angle}</p><h3 className="mt-5 text-sm font-semibold">为什么值得做</h3><p className="mt-2 text-sm leading-6 text-[var(--text-secondary)]">{item.whyRecommended}</p></Card><Card className="p-5"><h2 className="font-semibold">真实依据</h2><div className="mt-4 grid gap-3">{item.evidence.filter((evidence) => evidence.type !== "CREATOR_PROFILE").map((evidence) => { const snapshot = typeof evidence.snapshot === "object" && evidence.snapshot && !Array.isArray(evidence.snapshot) ? evidence.snapshot as Record<string, unknown> : {}; return <div key={evidence.id} className="rounded-xl border p-4"><Badge>{evidenceLabel[evidence.type] || "推荐依据"}</Badge><p className="mt-2 text-sm font-medium">{typeof snapshot.title === "string" ? snapshot.title : "已保存的推荐依据"}</p></div>; })}</div></Card><Card className="p-5"><h2 className="font-semibold">与你相关</h2><p className="mt-3 text-sm leading-6 text-[var(--text-secondary)]">{item.creatorFit}</p></Card></div><aside className="grid content-start gap-5"><Card className="p-5"><h2 className="font-semibold">{item.batch.mode === "AI_ASSISTED" ? "AI 建议" : "规则建议"}</h2><dl className="mt-4 grid gap-4 text-sm"><div><dt className="font-medium">为什么是现在</dt><dd className="mt-1 leading-6 text-[var(--text-secondary)]">{item.whyNow}</dd></div><div><dt className="font-medium">与近期内容的差异</dt><dd className="mt-1 leading-6 text-[var(--text-secondary)]">{item.differenceFromRecentContent}</dd></div></dl>{risks.length ? <div className="mt-5 border-t pt-4"><p className="text-sm font-medium">风险提示</p><ul className="mt-2 list-disc space-y-1 pl-5 text-sm text-[var(--text-secondary)]">{risks.map((risk) => <li key={risk}>{risk}</li>)}</ul></div> : null}</Card><Card className="p-5"><h2 className="font-semibold">下一步</h2><p className="mt-2 text-sm leading-6 text-[var(--text-secondary)]">{item.suggestedNextStep}</p><div className="mt-4"><RecommendationDetailActions itemId={item.id} canWrite={role !== "VIEWER"} contentIdeaId={item.contentIdeaId} projectId={item.projectId} /></div></Card></aside></div></div>;
}
