"use client";
import { Button, Input } from "@content-center/ui";
import { useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { Copy, Pencil } from "lucide-react";
import { EmailVerification } from "./email-verification";
import { AccountSessions } from "./account-sessions";
import { authClient } from "@/lib/auth-client";

export function ProfileSettings({ name, email, userId }: { name: string; email: string; userId?: string }) {
  const router=useRouter(); const submitting=useRef(false);
  const [message,setMessage]=useState(""); const [busy,setBusy]=useState(false); const [editing,setEditing]=useState(false); const [displayName,setDisplayName]=useState(name);
  async function copy(value:string,label:string) { try { await navigator.clipboard.writeText(value); setMessage(label+"已复制。"); } catch { setMessage("复制失败，请手动选中后复制。"); } }
  return <div className="settings-account" aria-busy={busy}>
    <h2 className="settings-subheading">账号信息</h2>
    <div className="settings-info-table"><div><span>名称</span>{editing ? <form className="settings-name-editor" onSubmit={async event=>{event.preventDefault(); if(submitting.current)return;submitting.current=true; const data=new FormData(event.currentTarget); setBusy(true); try {const value=String(data.get("name")); const result=await authClient.updateUser({name:value}); if(result.error) setMessage("姓名保存失败，请重试。"); else {setDisplayName(value);setEditing(false);setMessage("姓名已更新。");router.refresh();}} catch {setMessage("网络连接失败，请重试。");} finally {submitting.current=false;setBusy(false);} }}><Input name="name" aria-label="姓名" defaultValue={displayName} minLength={2} maxLength={80} required/><button className="settings-small-action" disabled={busy}>保存</button><button type="button" className="settings-small-action" disabled={busy} onClick={()=>setEditing(false)}>取消</button></form> : <button className="settings-inline-value" onClick={()=>setEditing(true)} aria-label="修改姓名">{displayName}<Pencil size={13}/></button>}</div><div><span>账号</span><button className="settings-inline-value" onClick={()=>void copy(email,"账号")} aria-label="复制账号">{email}<Copy size={13}/></button></div>{userId?<div><span>用户 ID</span><button className="settings-inline-value settings-uid" onClick={()=>void copy(userId,"用户 ID")} aria-label="复制用户 ID">{userId}<Copy size={13}/></button></div>:null}</div>
    <section className="settings-security"><h2 className="settings-subheading">账号安全</h2><details className="settings-password"><summary><span><strong>登录密码</strong><small>修改密码后，其他设备需要重新登录。</small></span><span className="settings-small-action">修改密码</span></summary><form className="grid gap-3 mt-4" onSubmit={async event=>{event.preventDefault();if(submitting.current)return;submitting.current=true;const form=event.currentTarget;const data=new FormData(form);setBusy(true);setMessage("");if(data.get("new")!==data.get("confirm")){setMessage("两次新密码不一致。");submitting.current=false;setBusy(false);form.querySelector<HTMLInputElement>('[name="confirm"]')?.focus();return;}try{const result=await authClient.changePassword({currentPassword:String(data.get("current")),newPassword:String(data.get("new")),revokeOtherSessions:true});if(result.error)setMessage("修改失败，请检查当前密码。新密码须为 8–128 位。");else{form.reset();setMessage("密码已修改，其他设备需要重新登录。安全通知邮件暂未配置。");}}catch{setMessage("网络连接失败，请重试。");}finally{submitting.current=false;setBusy(false);}}}><label>当前密码<Input name="current" type="password" autoComplete="current-password" required/></label><label>新密码<Input name="new" type="password" autoComplete="new-password" minLength={8} maxLength={128} required/></label><label>确认新密码<Input name="confirm" type="password" autoComplete="new-password" minLength={8} maxLength={128} required/></label><Button disabled={busy}>确认修改密码</Button></form></details></section>
    {message?<p role="status" className="mt-3">{message}</p>:null}
    <EmailVerification/>
    <AccountSessions/>
    <section className="settings-preferences"><div><div><h2>退出当前账号</h2><p>公司文件和项目会保留，可再次登录继续工作。</p></div><button className="settings-small-action" disabled={busy} onClick={async()=>{if(submitting.current)return;submitting.current=true;setBusy(true);try{const result=await authClient.signOut();if(result.error){setMessage("退出未完成，请检查网络后重试。");return;}window.location.assign("/login");}catch{setMessage("退出失败，请重试。");}finally{submitting.current=false;setBusy(false);}}}>退出登录</button></div></section>
  </div>;
}
export function WorkspaceSettings({ currentId, name, canManage, spaces }: { currentId: string; name: string; canManage: boolean; spaces: Array<{ id: string; name: string }> }) {
  const router=useRouter(); const submitting=useRef(false); const [message,setMessage]=useState(""); const [busy,setBusy]=useState(false);
  async function save(method:string,body:unknown){if(submitting.current)return;submitting.current=true;setBusy(true);setMessage("");try{const response=await fetch("/api/settings/workspace",{method,headers:{"content-type":"application/json"},body:JSON.stringify(body)});const result=await response.json();if(!response.ok)setMessage(result.message||"操作失败，请重新登录后重试。");else if(method==="POST")window.location.assign("/settings/workspace");else{setMessage("公司名称已保存。");router.refresh();}}catch{setMessage("网络连接失败，请重试。");}finally{submitting.current=false;setBusy(false);}}
  return <div><h2 className="settings-subheading">空间信息</h2><div className="settings-info-table"><div><span>当前公司</span><strong>{name||"没有可用空间"}</strong></div><div><span>管理权限</span><strong>{canManage?"可以管理公司设置":"查看与使用"}</strong></div></div>
    <section className="settings-preferences">{canManage?<div><div><h2>公司名称</h2><p>修改后对当前公司成员生效。</p></div><form className="settings-name-editor" action={data=>save("PATCH",{name:data.get("name")})}><Input aria-label="公司名称" name="name" defaultValue={name} minLength={2} maxLength={80} required/><button className="settings-small-action" disabled={busy}>保存</button></form></div>:null}
    {spaces.length>1?<div><div><h2>切换公司空间</h2><p>切换后重新载入工作台与该公司的配置。</p></div><form className="settings-name-editor" action={data=>save("POST",{workspaceId:data.get("workspaceId")})}><select aria-label="选择公司空间" name="workspaceId" defaultValue={currentId} className="rounded-lg border px-2">{spaces.map(space=><option key={space.id} value={space.id}>{space.name}</option>)}</select><button className="settings-small-action" disabled={busy}>进入</button></form></div>:spaces.length===1&&!currentId?<div><div><h2>可用公司空间</h2><p>{spaces[0]!.name}</p></div><button className="settings-small-action" disabled={busy} onClick={()=>void save("POST",{workspaceId:spaces[0]!.id})}>进入空间</button></div>:null}</section>
    {!spaces.length?<p className="settings-footnote">当前没有可用公司空间，请联系管理员恢复成员资格。</p>:null}{message?<p role="status">{message}</p>:null}
  </div>;
}
